### ISSUE TITLE
how to trancode alien(lua ffi ,which helps to call dll)  to wasm, please?

### ISSUE THREAD

**Issue by Ro798** [luttje/lua-wasm#3]
how to trancode alien(lua ffi ,which helps to call dll)  to wasm, please?
I want to call dlls in lua by webassembly, can it success?
alien
https://github.com/mascarenhas/alien

libffi
https://github.com/libffi/libffi

**Comment by luttje** [comment]
I can't help you with that.

Looking at the links you shared it seems well beyond the scope of this repo. This repo is just to compile Lua to WASM so you can then run Lua in the browser.

Perhaps you could re-purpose some of the build tools in this repo for your own use. Though again I would not be the right person to help you with that.

Good luck figuring out your problem!
